version: "2.19"
services:
  api:
    image: node:16.17.0
    command: sh -c "yarn install && yarn run start && yarn global add prisma"
    ports:
      - 3000:3333
    working_dir: /app
    volumes:
      - ./:/app

  database:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db

    environment:
      - MONGO_INITDB_DATABASE=blog
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
      - DATABASE_URL=mongodb://root:12345@localhost:27017/blog?authSource=admin
